# Дефолтные значения для сканирования директорий
# В scan_directories только параметр path обязателен. Остальные значения берутся из дефолтов:
default_exit_when_absent: false
default_patterns:
  - '*.crt'
  - '*.pem'
default_excludes: []
default_max_size: "-1m"
default_file_type: any
default_ignore_dir_links: false
default_recurse: true
default_scan_depth: 3

# Дефолтные значения для файлов метрик и прав доступа
# Локальные метрики будут доступны на каждом хосте в указанном пути
metrics_host_file_path: "/tmp/prom_host_certs_metr.txt"
# Агрегированные метрики будут доступны на хосте-агрегаторе
metrics_aggr_file_path: "/tmp/prom_aggr_certs_metr.txt"
metrics_owner: ansible    # Владелец файлов метрик
metrics_group: ansible    # Группа файлов метрик
metrics_mode: "0644"      # Права доступа к файлам метрик

# Настройки ролей хостов по умолчанию
# Хосты участвуют в сканировании сертификатов
metrics_host: true
# Хосты не участвуют в агрегации метрик (данные не отправляются на localhost)
metrics_aggregate: false
metrics_aggregate_delegate_host: localhost  # Хост для агрегации (требуется metrics_host: true)

# Пример конфигурации сканирования директорий
scan_directories:
  - path: "/etc"
    patterns:             # Поиск файлов сертификатов
      - '*.pem'
      - '*.crt'
    excludes: []          # Исключения (пустой список)
    file_type: file       # Тип сканируемых объектов
    max_size: "-1m"       # Размер файла меньше 1Mb
    depth: 10             # Глубина рекурсии (переопределяет default_scan_depth)
    ignore_dir_links: false
    recurse: true         # Рекурсивный поиск
  - path: "/usr"
    file_type: file       # Сканировать только файлы (по умолчанию)
