# Пример конфигурации сканирования директорий
# В scan_directories только параметр path обязателен. Не указанные значения берутся из дефолтов.
scan_directories:
  - path: "/etc"
    patterns:             # Поиск файлов сертификатов
      - '*.pem'
      - '*.crt'
    excludes: []          # Исключения (пустой список)
    file_type: file       # Тип сканируемых объектов
    max_size: "-1m"       # Размер файла меньше 1Mb
    depth: 10             # Глубина рекурсии (переопределяет default_scan_depth)
    ignore_dir_links: false
    recurse: true         # Рекурсивный поиск
  - path: "/usr"
    file_type: file

# Дефолтные значения для сканирования директорий (can_directories).
default_exit_when_absent: false
default_patterns:
  - '*.crt'
  - '*.pem'
default_excludes: []
default_max_size: "-1m"
default_file_type: any
default_ignore_dir_links: false
default_recurse: true
default_scan_depth: 3

# Настройки ролей хостов по умолчанию
# Хосты учавствуют в сканировании сертификатов и создании локальных метрик
metrics_host: true
# Хосты участвуют в агрегации метрик (данные для агрегации отправляются на localhost)
metrics_aggregate_delegate_host: localhost  # Хост для агрегации локальных метрик с текущего хоста (требуется metrics_host: true).

# Дефолтные значения для файлов метрик
# Локальные метрики будут доступны на текущем хосте по указанному пути.
# Если на данном хосте собирались локальные метрики (metrics_host: true).
metrics_host_file_path: "/var/lib/metrics/prom_host_certs_metr.txt"
# Агрегированные метрики будут доступны на текущум хосте по указанному пути.
# Если на данный хост делегировались метрики для агрегации (metrics_aggregate_delegate_host).
metrics_aggr_file_path: "/var/lib/metrics/prom_aggr_certs_metr.txt"

# Дефолтные значения прав доступа для файлов метрик
metrics_owner: ansible    # Владелец файлов метрик
metrics_group: ansible    # Группа файлов метрик
metrics_file_mode: "0644"      # Права доступа к файлам метрик
metrics_dir_mode: "0755"      # Права доступа к директории метрик
