---
- name: Set Local Scanner true if all conditions met
  ansible.builtin.set_fact:
    ci_local_scanner: true
  when:
    - (ci_scan_directories | default([]) | selectattr('path', 'defined') | map(attribute='path') | map('trim') | select('ne', '') | list | length) > 0

- name: Validate and set Aggregate Host fact
  ansible.builtin.set_fact:
    ci_metrics_aggregate_host: >-
      {%- set target_host = ci_metrics_aggregate_host | default('') | trim -%}
      {%- if target_host and target_host in groups['all'] -%}
      {{ target_host }}
      {%- else -%}
      {{ inventory_hostname }}
      {%- endif -%}

- name: Set Local Receiver true if all conditions met
  ansible.builtin.set_fact:
    ci_local_receiver: true
  when:
    inventory_hostname in
    (ansible_play_hosts |
     map('extract', hostvars) |
     selectattr('ci_metrics_aggregate_host', 'defined') |
     map(attribute='ci_metrics_aggregate_host') |
     select('match', '.+') |
     unique | list)

