---
- name: Import Init tasks
  ansible.builtin.import_tasks: init.yml
  tags:
    - always
    - ci_init

- name: Import Inspector tasks
  ansible.builtin.import_tasks: inspector.yml
  tags:
    - always
    - ci_inspector

- name: Import Nginx tasks
  ansible.builtin.import_tasks: nginx.yml
  tags:
    - never
    - ci_nginx

- name: Import Prometheus tasks
  ansible.builtin.import_tasks: prometheus.yml
  tags:
    - never
    - ci_prometheus

- name: Import Pushgateway tasks
  ansible.builtin.import_tasks: pushgateway.yml
  tags:
    - never
    - ci_pushgateway
