---
- name: Import Inspector tasks
  import_tasks: inspector.yml
  tags:
    - always
    - inspector

- name: Import setup Nginx tasks
  import_tasks: nginx.yml
  when:
    - (aggregate_exporter | default(false)) or
      (local_exporter | default(false))
  tags:
    - never
    - nginx
