---
- name: Import Inspector tasks
  ansible.builtin.import_tasks: inspector.yml
  tags:
    - always
    - ci_inspector

- name: Import Nginx tasks
  ansible.builtin.import_tasks: nginx.yml
  when:
    - (aggregate_exporter | default(false)) or
      (local_exporter | default(false))
  tags:
    - never
    - ci_nginx
