---
- name: Import Init tasks
  ansible.builtin.import_tasks: init.yml
  tags:
    - always
    - ci_init

- name: Import Scan and Agregate tasks
  ansible.builtin.import_tasks: scan.yml
  tags:
    - always
    - ci_scan

- name: Import Local Exporter tasks
  ansible.builtin.import_tasks: local.yml
  tags:
    - always
    - ci_local

- name: Import Nginx Server tasks
  ansible.builtin.import_tasks: nginx.yml
  tags:
    - never
    - ci_nginx

- name: Import Prometheus Server tasks
  ansible.builtin.import_tasks: prometheus.yml
  tags:
    - never
    - ci_prometheus

- name: Import Pushgateway Exporter tasks
  ansible.builtin.import_tasks: pushgateway.yml
  tags:
    - never
    - ci_pushgateway
