---
- name: Set nginx_conf_path with fallback
  ansible.builtin.set_fact:
    nginx_conf_path: >-
      {{
        "/etc/nginx/sites-available" if ansible_os_family == "Debian"
        else "/etc/nginx/conf.d" if ansible_os_family == "RedHat"
        else "/etc/nginx"
      }}
  when: nginx_conf_path is not defined

- name: Set nginx_enabled_conf_path with fallback
  ansible.builtin.set_fact:
    nginx_enabled_conf_path: >-
      {{
        "/etc/nginx/sites-enabled" if ansible_os_family == "Debian"
        else "/etc/nginx/conf.d" if ansible_os_family == "RedHat"
        else "/etc/nginx"
      }}
  when: nginx_enabled_conf_path is not defined

- name: Set nginx_link_conf_type with fallback
  ansible.builtin.set_fact:
    nginx_link_conf_type: >-
      {{
        "link" if ansible_os_family == "Debian"
        else "hard" if ansible_os_family == "RedHat"
        else "hard"
      }}
  when: nginx_link_conf_type is not defined


- block:
    - name: Install Nginx/Angie
      ansible.builtin.package:
        name: "{{ nginx_package }}"
        state: present

    - name: Generate .htpasswd file
      community.general.htpasswd:
        path: /etc/nginx/.htpasswd
        name: "{{ auth_user }}"
        password: "{{ auth_password }}"
        state: present
        owner: root
        group: www-data
        mode: '0640'

    - name: Deploy metrics Nginx config
      ansible.builtin.template:
        src: ci_metrics.conf.j2
        dest: "{{ nginx_conf_path }}/ci_{{ inventory_hostname }}_metrics.conf"
        owner: root
        group: root
        mode: 0644
      notify: Reload Nginx

    - name: Enable metrics Nginx config
      ansible.builtin.file:
        src: "{{ nginx_conf_path }}/ci_{{ inventory_hostname }}_metrics.conf"
        dest: "{{ nginx_enabled_conf_path }}/ci_{{ inventory_hostname }}_metrics.conf"
        state: "{{ nginx_link_conf_type }}"
      notify: Reload Nginx

  become: yes
  when:
    - nginx_conf_path | default('') | trim | length > 0
    - nginx_enabled_conf_path | default('') | trim | length > 0
    - nginx_link_conf_type | default('') | trim | length > 0
    - (local_exporter | default(false)) or (aggregate_exporter | default(false))
