---
- name: Get only needs facts
  ansible.builtin.setup:
    filter: "{{ item }}"
  when:
    - local_metrics_port | default('') | trim | length > 0
    - ci_local_receiver | default(false)
    - ci_metrics_local_file | default('') | trim | length > 0
  loop:
    - ansible_host

- name: Set ci_prometheus_local_target
  ansible.builtin.set_fact:
    ci_prometheus_local_target: "{{ ansible_host }}:{{ local_metrics_port }}"
  when:
    - local_metrics_port | default('') | trim | length > 0
    - ci_local_receiver | default(false)
    - ci_metrics_local_file | default('') | trim | length > 0
    - ansible_host | default(false)

- name: Generate targets file for Prometheus
  ansible.builtin.template:
    src: ci_targets.yml.j2
    dest: "{{ ci_targets_file }}"
  when:
    - ci_targets_file | default('') | trim | length > 0

