---
- name: Prepare and send metrics to Pushgateway
  ansible.builtin.uri:
    url: "http://{{ci_pushgateway_host}}/metrics/job/cert_expiry/instance/{{ inventory_hostname }}"
    method: POST
    body: "{{ lookup('template', 'templates/ci_metrics.prom.j2') }}"
    body_format: raw
    headers:
      Content-Type: text/plain
  when:
    - ci_pushgateway_exporter | default(false)

