---
auth_user: "metrics_user"
auth_password: "secure_password"
local_metrics_port: 8880
aggregated_metrics_port: 8881

# Дистрибутив-специфичные переменные
nginx_package: "nginx"
nginx_service_name: "nginx"
nginx_conf_path: "{{ (ansible_os_family == 'Debian') | ternary('/etc/nginx/sites-available', '/etc/nginx/conf.d') }}"
